# Generated by Django 3.2.20 on 2023-08-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('deleted', 'Deleted'), ('active', 'Active'), ('waitingapproval', 'Waiting approval')], default='active', max_length=50),
        ),
    ]
