# Generated by Django 3.2.20 on 2023-08-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230831_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='keyword',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('deleted', 'Deleted'), ('active', 'Active'), ('waitingapproval', 'Waiting approval')], default='active', max_length=50),
        ),
    ]
